name: test

on:
  pull_request_target:
    types: 
      - opened
      - synchronize
      - reopened
      - edited
    branches:
      - devop/gha

# ! danger !:
# https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#understanding-the-risk-of-script-injections
jobs:
  prt:
    # TODO: if: name PR starts with ...
    runs-on: ubuntu-18.04
    steps:
      - name: echo
        run: |
          echo "github: ${{ toJSON(github) }}"
          echo "repo_name: ${{ github.event.pull_request.base.repo.name  }}"
          echo "repo_owner: ${{ github.event.pull_request.base.repo.owner.login }}"
          echo "head_label: ${{ github.event.pull_request.head.label }}"
          echo "base_ref: ${{ github.event.pull_request.base.ref }}"
          echo "----------------------------------"
          echo "head_ref_2: ${{ github.head_ref }}"
          echo "base_ref_2: ${{ github.base_ref }}"

      # checkout repo/branch being pushed to
      # https://github.com/actions/checkout
      - name: "base: checkout"
        uses: actions/checkout@v2
        with:
          ref: ${{ github.base_ref }}

      - name: "install NodeJS"
        uses: actions/setup-node@v2
        with:
          # cache npm dependencies
          # https://github.com/actions/setup-node#caching-packages-dependencies
          cache: 'npm'
          node-version: 16.13.2
          registry-url: "https://registry.npmjs.org/"

      - name: set NPM version
        run: npm i -g npm@6.14.16

      - name: create .env file
        run: |
          echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" > .env
          # cp .env.example .env
          # sed -i'' "s/^GITHUB_TOKEN=/GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}/" .env

      #  ensure only valid changes have been made
      - name: "base: install, build, test"
        run: |
          npm ci
          # TODO: comment testing back in
          # npm run test
          npm run build

      # https://github.community/t/how-do-you-figure-out-if-a-pr-is-from-a-work-in-pull-request-target-workflows/170001
      # https://docs.github.com/en/rest/reference/repos#get-a-repository
      - name: "base: validate head changes"
        run: |
          node dist/bin.js \
            validate-git-diffs \
            --token="${{ secrets.GITHUB_TOKEN }}" \
            --repo="${{ github.event.pull_request.base.repo.name  }}" \
            --owner="${{ github.event.pull_request.base.repo.owner.login }}" \
            --head="${{ github.event.pull_request.head.label }}" \
            --base="${{ github.event.pull_request.base.ref }}"

      # checkout the head now that we've verified it's safe
      - name: "base: checkout"
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: create .env file
        run: |
          echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" > .env
          # cp .env.example .env
          # sed -i'' "s/^GITHUB_TOKEN=/GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}/" .env

      - name: "base: install, build, test"
        run: |
          npm ci
          npm run test
          npm run build

      - name: "base: verify"
        run: |
          node dist/bin.js \
            validate-git-diffs \
            --token=${{ secrets.GITHUB_TOKEN }} \
            --repo="${{ github.event.pull_request.base.repo.name  }}" \
            --owner="${{ github.event.pull_request.base.repo.owner.login }}" \
            --head="${{ github.event.pull_request.head.label }}" \
            --base="${{ github.event.pull_request.base.ref }}" \
            --verify


      # # https://github.com/actions/setup-node
      # - name: change something
      #   run: base64 /dev/urandom | head -c 10 | tr -d '\n' >> random.txt

      # # new PR
      # # https://github.com/marketplace/actions/create-pull-request
      # # this *shouldn't* work because we're on the pull_request event
      # # > Note: If you want pull requests created by this action to trigger an
      # # on: push or on: pull_request workflow then you cannot use the default
      # # GITHUB_TOKEN. See the documentation here for workarounds.
      # # https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#triggering-further-workflow-runs
      # - name: Create Pull Request
      #   uses: peter-evans/create-pull-request@v3
      #   # with:
      #   #     base: ${{ github.base_ref }}


      # # get added files
      # - name: get git changes
      #   uses: lots0logs/gh-action-get-changed-files@2.1.4
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}

      # # print changes
      # - name: 'view changes'
      #   run: |
      #       echo "=== files: ==="
      #       cat ~/files.json

      #       echo "=== added: ==="
      #       cat ~/files_added.json

      #       echo "=== modified: ==="
      #       cat ~/files_modified.json

      #       echo "=== removed: ==="
      #       cat ~/files_removed.json

      # - name: files2
      #   id: files
      #   uses: jitterbit/get-changed-files@v1

      # # print changes
      # - name: view changes 2
      #   run: |
      #       for changed_file in ${{ steps.files.outputs.all }}; do
      #         echo "file: ${changed_file}."
      #       done

      # fetch origin target
      # fetch 

