name: Validate Contracts

on:
  pull_request_target:
    types: 
      - opened
      - synchronize
      - reopened
      - edited
    branches:
      - devop/gha

# ! danger !:
# https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#understanding-the-risk-of-script-injections
jobs:
  Validate:
    # TODO: if: name PR starts with ...
    runs-on: ubuntu-18.04
    steps:
      - name: echo
        run: |
          echo "repo_name: ${{ github.event.pull_request.base.repo.name  }}"
          echo "repo_owner: ${{ github.event.pull_request.base.repo.owner.login }}"
          echo "head_label: ${{ github.event.pull_request.head.label }}"
          echo "base_ref: ${{ github.event.pull_request.base.ref }}"
          echo "----------------------------------"
          echo "head_ref_2: ${{ github.head_ref }}"
          echo "base_ref_2: ${{ github.base_ref }}"
          echo "----------------------------------"
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          echo "----------------------------------"
          echo "repo: ${{ github.event.pull_request.base.label }}"
          echo "clone_url: ${{ github.event.pull_request.base.repo.clone_url }}"
          echo "ref: ${{ github.base_ref }}"

      # checkout repo/branch being pushed to
      # https://github.com/actions/checkout
      - name: "base: checkout"
        uses: actions/checkout@v2
        with:
          # owner / repo
          repository: ${{ github.event.pull_request.base.repo.full_name }}
          # branch
          ref: ${{ github.event.pull_request.base.ref }}

      - name: "base: git whoami"
        run: |
          git status
          git branch -v
          git remote -v

      - name: install NodeJS
        uses: actions/setup-node@v2
        with:
          # cache npm dependencies
          # https://github.com/actions/setup-node#caching-packages-dependencies
          cache: 'npm'
          node-version: 16.13.2
          registry-url: "https://registry.npmjs.org/"

      - name: set NPM version
        run: npm i -g npm@6.14.16

      - name: create .env file
        run: |
          echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" > .env
          # cp .env.example .env
          # sed -i'' "s/^GITHUB_TOKEN=/GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}/" .env

      #  ensure only valid changes have been made
      - name: "base: install, build, test"
        run: |
          npm ci
          # TODO: comment testing back in
          npm run test
          npm run build

      # https://github.community/t/how-do-you-figure-out-if-a-pr-is-from-a-work-in-pull-request-target-workflows/170001
      # https://docs.github.com/en/rest/reference/repos#get-a-repository
      - name: "base: validate head changes"
        run: |
          node dist/bin.js \
            validate-git-diffs \
            --token="${{ secrets.GITHUB_TOKEN }}" \
            --repo="${{ github.event.pull_request.base.repo.name  }}" \
            --owner="${{ github.event.pull_request.base.repo.owner.login }}" \
            --head="${{ github.event.pull_request.head.label }}" \
            --base="${{ github.event.pull_request.base.ref }}" \
            --verbose \
            --strict

      # checkout the head now that we've verified it's safe
      - name: "head: checkout"
        uses: actions/checkout@v2
        with:
          # owner / repo
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          # branch
          ref: ${{ github.event.pull_request.head.ref }}

      - name: "head: git whoami"
        run: |
          git status
          git branch -v
          git remote -v

      - name: create .env file
        run: |
          echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" > .env
          # cp .env.example .env
          # sed -i'' "s/^GITHUB_TOKEN=/GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}/" .env

      - name: "base: install, build, test"
        run: |
          npm ci
          npm run test
          npm run build

      - name: "base: verify"
        run: |
          node dist/bin.js \
            validate-git-diffs \
            --token=${{ secrets.GITHUB_TOKEN }} \
            --repo="${{ github.event.pull_request.base.repo.name  }}" \
            --owner="${{ github.event.pull_request.base.repo.owner.login }}" \
            --head="${{ github.event.pull_request.head.label }}" \
            --base="${{ github.event.pull_request.base.ref }}" \
            --strict \
            --verbose \
            --verify
