name: validate

on:
  pull_request_target:
    types: 
      - opened
      - synchronize
      - reopened
    branches:
      - test/gha

jobs:
  validate:
    runs-on: ubuntu-18.04
    steps:
      # get added files
      - name: get git changes
        uses: lots0logs/gh-action-get-changed-files@2.1.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # print changes
      - name: 'view changes'
        run: |
            echo "=== files: ==="
            cat ~/files.json

            echo "=== added: ==="
            cat ~/files_added.json

            echo "=== modified: ==="
            cat ~/files_modified.json

            echo "=== removed: ==="
            cat ~/files_removed.json