# https://docs.github.com/en/actions
name: validate

on:
  pull_request:
    types: 
      - opened
      - synchronize
    branches:
      - test/gha

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      # checkout code on the branch
      - uses: actions/checkout@v2
      # https://github.com/actions/setup-node
      - uses: actions/setup-node@v2
        with:
          # cache npm dependencies
          # https://github.com/actions/setup-node#caching-packages-dependencies
          cache: 'npm'
          node-version: 16.13.2
          registry-url: "https://registry.npmjs.org/"
      - run: npm i -g npm@6.14.16
      - run: npm ci
      - run: npm run test
      - run: npm run build
      - run: git --no-pager branch -v
      - run: git status
      - run: git --no-pager diff origin/main HEAD
      - run: git --no-pager diff origin/test/gha HEAD
      - run: git --no-pager diff --name-status origin/test/gha HEAD | ./scripts/diffs.sh --verbose --strict
      - run: "echo result: \"$?\""
