#
# Execute tests and Validate new contracts on pull request
#
# Checks whether added contracts are valid
#
# TODO: do not execute scripts from the pulled-in branch...
#

name: validate

on:
  pull_request:
    types: 
      - opened
      - synchronize
    branches:
      - test/gha

jobs:
  validate:
    runs-on: ubuntu-18.04
    steps:
      # checkout code on the branch
      - uses: actions/checkout@v2
      # https://github.com/actions/setup-node

      # - uses: actions/setup-node@v2
      #   with:
      #     # cache npm dependencies
      #     # https://github.com/actions/setup-node#caching-packages-dependencies
      #     cache: 'npm'
      #     node-version: 16.13.2
      #     registry-url: "https://registry.npmjs.org/"

      # - run: npm i -g npm@6.14.16
      # - run: npm ci
      # - run: npm run test
      # - run: npm run build
      # # https://github.com/actions/checkout/issues/160
      # # fetch all branches from remote so we can diff with the current branch
      # - run: git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*

      - name: generate variables
        id: vars
        run: |
          chainid=1
          provideruri=$(grep -E "^$chainid\s+" nodes | awk '{ print $2 }')
          if [[ ! "$provideruri" ]]; then echo "no node for chainid $chainid"; exit 1; fi
          primarybranch="origin/test/gha"

          echo "::set-output name=chainid::$chainid"
          echo "::set-output name=provideruri::$provideruri"
          echo "::set-output name=primarybranch::$primarybranch"

          echo "chainid: $chainid"
          echo "provideruri: $provideruri"
          echo "primarybranch: $primarybranch"

      - uses: lots0logs/gh-action-get-changed-files@2.1.4

      - name: get changed files
        run: |
          chainid="${{ steps.vars.outputs.chainid }}"
          provideruri="${{ steps.vars.outputs.provideruri }}"
          # $added=git --no-pager diff origin/test/gha HEAD
          # echo "getting changed files"

          echo "=========== all"
          cat ~/files.json

          echo "=========== modified"
          cat ~/files_modified.json

          echo "=========== added"
          cat ~/files_added.json

          echo "=========== deleted"
          cat ~/files_deleted.json

          echo "=========== renamed"
          cat ~/files_renamed.json


      # # get the desired node
      # - id: provideruri
      #   run: |
      #     chainid="${{ steps.chainid.outputs.chainid }}"

      # - run: |
      #       echo "chainid:"
      #       echo "chainid: ${{ steps.vars.outputs.chainid }}"
      #       echo "provideruri:"
      #       echo "chainid: ${{ steps.vars.outputs.provideruri }}"

      # - run: git --no-pager diff origin/test/gha HEAD
      # - run: |
      #     git \
      #       --no-pager \
      #       diff \
      #       --name-status \
      #       origin/test/gha HEAD \
      #       | ./scripts/diffs.sh \
      #         - \
      #         --verbose \
      #         --provider-uri=https://nodes.mewapi.io/rpc/eth
      # - run: "echo result: \"$?\""
